<a href="https://colab.research.google.com/github/MasahiroAraki/SpeechRecognition/blob/master/Python/chap10a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 例題10.1

図10.6に示すHMMが与えられているとき、特徴ベクトルの系列を入力するとその出力確率を計算するPythonのコードを作成せよ。

In [1]:
import numpy as np

遷移確率と出力確率の定義

In [2]:
# transit probability
a = np.array([[0.0, 1.0, 0.0, 0.0],
              [0.0, 0.8, 0.2, 0.0],
              [0.0, 0.0, 0.5, 0.5],
              [0.0, 0.0, 0.0, 0.0]])
# output probability
b = np.array([[0.0, 0.0],
              [0.6, 0.4],
              [0.5, 0.5],
              [0.0, 0.0]])

特徴ベクトル系列の定義

Aを0、Bを1で表す

In [3]:
X = np.array([0,0,1])

系列の出力確率の計算

In [4]:
numStates = a.shape[0]
inputLen = X.shape[0]

node = np.zeros((numStates, inputLen))

In [5]:
# state=1, t=0
node[1, 0] = b[1, X[0]]

In [6]:
for t in range(1, inputLen):
  for s in range(1, numStates-1):
    inputs = [b[s, X[t]]*a[u, s]*node[u, t-1] for u in range(1, numStates-1)]
    node[s, t] = np.sum(inputs)

In [7]:
node

array([[0.     , 0.     , 0.     ],
       [0.6    , 0.288  , 0.09216],
       [0.     , 0.06   , 0.0438 ],
       [0.     , 0.     , 0.     ]])

終了状態への遷移確率を掛けて系列の出力確率を求める

In [8]:
node[numStates-2, inputLen-1] * a[numStates-2, numStates-1]

0.0219

## 例題10.2

図10.7に示すHMMが与えられているとき、特徴ベクトルの系列を入力するとその出力確率を計算するPythonのコードを作成せよ。

In [9]:
import numpy as np


遷移確率と出力確率の定義

In [10]:
# transit probability
a = np.array([[0.0, 1.0, 0.0, 0.0, 0.0],
              [0.0, 0.8, 0.2, 0.0, 0.0],
              [0.0, 0.0, 0.4, 0.6, 0.0],
              [0.0, 0.0, 0.0, 0.5, 0.5],
              [0.0, 0.0, 0.0, 0.0, 0.0]])
# output probability
b = np.array([[0.0, 0.0],
              [0.7, 0.3],
              [0.5, 0.5],
              [0.2, 0.8],
              [0.0, 0.0]])

特徴ベクトル系列の定義

Aを0、Bを1で表す

In [11]:
X = np.array([0,0,0,1,1])

系列の出力確率の計算


In [12]:
numStates = a.shape[0]
inputLen = X.shape[0]

node = np.zeros((numStates, inputLen))

In [13]:
# state=1, t=0
node[1, 0] = b[1, X[0]]

In [14]:
for t in range(1, inputLen):
  for s in range(1, numStates-1):
    inputs = [b[s, X[t]]*a[u, s]*node[u, t-1] for u in range(1, numStates-1)]
    node[s, t] = np.sum(inputs)

In [15]:
node

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.7       , 0.392     , 0.21952   , 0.0526848 , 0.01264435],
       [0.        , 0.07      , 0.0532    , 0.032592  , 0.01178688],
       [0.        , 0.        , 0.0084    , 0.028896  , 0.02720256],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

終了状態への遷移確率を掛けて系列の出力確率を求める

In [16]:
node[numStates-2, inputLen-1] * a[numStates-2, numStates-1]

0.013601279999999999

ビタビアルゴリズムに変更し、図10.10の結果を確認

In [17]:
numStates = a.shape[0]
inputLen = X.shape[0]

node = np.zeros((numStates, inputLen))
bp = np.zeros((numStates, inputLen))

In [18]:
# state=1, t=0
node[1, 0] = b[1, X[0]]

In [19]:
for t in range(1, inputLen):
  for s in range(1, numStates-1):
    inputs = [b[s, X[t]]*a[u, s]*node[u, t-1] for u in range(1, numStates-1)]
    node[s, t] = np.max(inputs)
    bp[s, t] = np.argmax(inputs) + 1

In [20]:
node

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.7       , 0.392     , 0.21952   , 0.0526848 , 0.01264435],
       [0.        , 0.07      , 0.0392    , 0.021952  , 0.00526848],
       [0.        , 0.        , 0.0084    , 0.018816  , 0.01053696],
       [0.        , 0.        , 0.        , 0.        , 0.        ]])

終了状態への遷移確率を掛けて系列の出力確率を求める

In [21]:
node[numStates-2, inputLen-1] * a[numStates-2, numStates-1]

0.00526848

In [22]:
bp

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1.],
       [0., 1., 1., 1., 1.],
       [0., 1., 2., 2., 2.],
       [0., 0., 0., 0., 0.]])